### ISSUE TITLE
Advice for creating golang version of this

### ISSUE THREAD

**Issue by m3dwards** [wbolster/evil-text-object-python#5]
Thanks for offering to give me some tips. I'm no emacs lisp developer.

I've had a brief look and I'm not sure how you detect what is a function is etc. I was perhaps expecting some regular expressions. Is there any chance you can give a brief explanation on how this works and what might be equivalents in a different language?

Very grateful for any insight you can offer.

**Comment by m3dwards** [comment]
You are requiring python but I don't see it in melpa? https://melpa.org/#/python

**Comment by m3dwards** [comment]
Copied what looked like boilerplate: https://github.com/maxwedwards/evil-text-object-go/blob/master/evil-text-object-go.el

**Comment by m3dwards** [comment]
tbh, I think I've got a fair bit of reading to do. I can't even figure out how to get what I have so far to run.

**Comment by m3dwards** [comment]
Got it loaded into emacs and added a simple implementation that just selects next two lines. I'll have a look in the `go-mode` package to see if there is anything in there that can help with moving to functions. Still don't know where your python package comes from.

**Comment by wbolster** [comment]
sorry no time to look into this so far, but you're on the right track. the python-nav helpers come from the built-in python.el.

the main idea is that you define a text object by figuring out the beginning and end, and returning that. save-excursion and programming language specific navigation helpers (or regex search) can help you do this.

**Comment by m3dwards** [comment]
ok, I have something that selects whole functions, not got statements as I couldn't see anything in go-mode that would help with that. There are probably lots of edge cases that don't work but I think it might be time to try and get it on melpa.
